#!/bin/bash

xrdb -merge ~/.Xresources
xscreensaver -no-splash &
# For some reason disabling the TrackPad in the BIOS of the
# X1 Carbon doesn't work -- this is obviously not portable
xinput set-prop 11 147 0
